### ISSUE TITLE
issues with error — Given usernames could not be requested

### ISSUE THREAD

**Issue by aalexanderr** [dropseed/pullapprove#65] opened 2022-12-23 12:30 UTC
Two examples that we are getting this error msg on:
https://github.com/project-chip/connectedhomeip/pull/23612 (this user has other PRs in this repo that work)
https://github.com/project-chip/connectedhomeip/pull/23908 (this pull initially passed pullapprove but after one of the rebases/ merges started throwing title error msg)

Is there anything we can do to fix this?

Some potentially relevant info - i have 2 e-mail addresses connected to the gh acc, maybe thats whats tipping it over?

**Comment by davegaeddert** [comment] 2022-12-23 15:49
Hey @aalexanderr — looks like the specific account it's having an issue with is @ksperling-apple. Is there something that might have changed there (permissions, team/org membership, etc.)? Hope that helps!

**Comment by davegaeddert** [comment] 2022-12-23 15:50
Note that if you think the issue is resolved, any update to the PR will trigger it to run again (adding/removing a label is always an easy one if no other activity).

**Comment by davegaeddert** [comment] 2022-12-26 20:30
I'm going to close this for now — let me know if you're still having issues!

**Closed by davegaeddert** 2022-12-26 20:30 UTC

**Comment by bzbarsky-apple** [comment] 2023-01-03 14:05
@davegaeddert That account was recently (as of when this issue was filed) added to a reviewers group, but should generally be fine...

**Comment by davegaeddert** [comment] 2023-01-27 19:47
Hey @aalexanderr @bzbarsky-apple — sorry, this fell off my radar. It looks like there are still some username issues coming through:
![CleanShot 2023-01-27 at 13 43 59](https://user-images.githubusercontent.com/649496/215183042-6859999a-3f50-41e6-87b7-49393c51371d.png)

Unfortunately I don't know exactly which of these is the problem, but what I'd suggest is simply going to https://github.com/project-chip/connectedhomeip/pull/23951 and clicking the reviewer dropdown and see which one of those people doesn't show up! Again, sorry I'm slow to get back to this.

**Comment by bzbarsky-apple** [comment] 2023-01-28 00:49
> and see which one of those people doesn't show up! 

All four of them show up in the autocomplete if I start typing their names in....

**Comment by davegaeddert** [comment] 2023-01-30 17:53
Geez. Ok, I've turned on some additional logging to see if I can get to the bottom of it. If not, I should have more info to ask GitHub support if they can tell what the issue is... I'll check later in the week and see if any new ones have come through.

**Comment by davegaeddert** [comment] 2023-02-06 17:47
I've opened a ticket with GitHub about this, just fyi.

**Comment by davegaeddert** [comment] 2023-02-08 17:35
@bzbarsky-apple @aalexanderr here's the response from GitHub so far...
![CleanShot 2023-02-08 at 11 33 48](https://user-images.githubusercontent.com/649496/217607818-6c725829-f80c-4498-b3d3-454b9d710e17.png)

**Comment by davegaeddert** [comment] 2023-02-14 16:56
Alright, so the gist is that the PR "is in a bad state". There's a known issue with the GitHub API where requesting reviews too quickly can cause multiple review requests to exist for the same user, and that's causing the validation error later. They're working on it but also said it depends on some other projects, so who knows. I've known about this issue for a while and basically have a jitter on requesting reviews to mitigate it — I went ahead and increased that potential delay, so hopefully we get less of these going forward.

I'll keep an eye on it, but let me know if it continues to be a problem.
